export const gatewayContract = {
  health: '/health',
  mesh: '/operator/mesh',
  ledger: '/operator/ledger',
  ledgerArtifacts: '/operator/ledger/artifacts',
  ledgerArtifact: (artifactId: string) => `/operator/ledger/artifacts/${encodeURIComponent(artifactId)}`,
  deployables: '/operator/deployables',
  deploymentPosture: '/operator/deployment/posture',
  assuranceReport: '/operator/assurance/report',
  assuranceAttest: '/operator/assurance/attest',
  metaAuthority: '/operator/meta-authority',
  envelopes: '/operator/envelopes',
  osState: '/operator/os/state',
  osMissions: '/operator/os/missions',
  autonomyTick: '/operator/os/autonomy/tick',
  nextTask: (agentId?: string) => `/operator/os/tasks/next${agentId ? `?agentId=${encodeURIComponent(agentId)}` : ''}`,
  taskActions: (taskId: string) => `/operator/os/tasks/${taskId}/actions`,
  executeTaskAction: (taskId: string, actionId: string) => `/operator/os/tasks/${taskId}/actions/${actionId}/execute`,
  claimTask: (taskId: string) => `/operator/os/tasks/${taskId}/claim`,
  heartbeatTask: (taskId: string) => `/operator/os/tasks/${taskId}/heartbeat`,
  completeTask: (taskId: string) => `/operator/os/tasks/${taskId}/complete`,
  retryTask: (taskId: string) => `/operator/os/tasks/${taskId}/retry`,
  registerAgent: '/operator/os/agents',
  renewLease: (leaseId: string) => `/operator/os/leases/${leaseId}/renew`,
  createWorkspace: '/operator/os/workspaces',
  advanceMission: (missionId: string) => `/operator/os/missions/${missionId}/advance`,
  compilePolicy: '/operator/policy/compile',
  govern: '/operator/govern',
  killSwitch: '/operator/kill-switch',
  replay: (traceId: string) => `/operator/replay/${traceId}`,
  counterfactual: '/operator/replay/counterfactual',
};
