// Embed openapi.json (source of truth at adapters/http-gateway/openapi.json)
// into this package as both:
//   - <package-root>/openapi.json (a copy shipped in the npm tarball under files[])
//   - src/openapi-spec.gen.ts (an embedded string + parsed object so the published
//     dist/ is self-contained and consumers can `import { OPENAPI_YAML, OPENAPI_SPEC }`).
//
// Note on the constant name: the export is called `OPENAPI_YAML` for legacy /
// task-spec reasons (the operator-facing concept is "the OpenAPI spec") even
// though the artifact happens to be JSON. The JSON IS valid YAML.

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from "node:fs";
import { dirname, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const repoRoot = resolve(pkgRoot, "..", "..");
const sourceSpec = resolve(repoRoot, "adapters", "http-gateway", "openapi.json");
const localCopy  = resolve(pkgRoot, "openapi.json");
const embeddedTs = resolve(pkgRoot, "src", "openapi-spec.gen.ts");

if (!existsSync(sourceSpec)) {
  console.error(`embed-openapi: source spec not found at ${sourceSpec}`);
  process.exit(1);
}

const raw = readFileSync(sourceSpec, "utf8");

// Re-parse + re-serialize so the embedded string is canonical (2-space indent,
// trailing newline) regardless of how the source was edited.
let parsed;
try {
  parsed = JSON.parse(raw);
} catch (err) {
  console.error(`embed-openapi: source spec is not valid JSON: ${err.message}`);
  process.exit(1);
}

const canonical = `${JSON.stringify(parsed, null, 2)}\n`;
writeFileSync(localCopy, canonical, "utf8");

mkdirSync(dirname(embeddedTs), { recursive: true });
const banner =
  "// AUTO-GENERATED by packages/gateway-client/scripts/embed-openapi.mjs\n" +
  "// Source of truth: adapters/http-gateway/openapi.json\n" +
  "// Do not edit by hand — regenerated by `pnpm --filter @aristotle/gateway-client build`.\n";

// Escape the canonical JSON for a JS string literal.
const escaped = canonical
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const content =
  `${banner}` +
  `\n/** Raw OpenAPI 3.1 spec for the AristotleOS execution-control HTTP boundary, as a string. */\n` +
  `export const OPENAPI_YAML: string = \`${escaped}\`;\n` +
  `\n/** Parsed OpenAPI 3.1 spec object. */\n` +
  `export const OPENAPI_SPEC: Readonly<Record<string, unknown>> = Object.freeze(${JSON.stringify(parsed, null, 2)}) as Readonly<Record<string, unknown>>;\n` +
  `\n/** OpenAPI version string, e.g. "3.1.0". */\n` +
  `export const OPENAPI_VERSION: string = ${JSON.stringify(parsed.openapi ?? "")};\n` +
  `\n/** Title from \`info.title\`. */\n` +
  `export const OPENAPI_TITLE: string = ${JSON.stringify(parsed.info?.title ?? "")};\n` +
  `\n/** API version from \`info.version\`. */\n` +
  `export const OPENAPI_API_VERSION: string = ${JSON.stringify(parsed.info?.version ?? "")};\n` +
  `\n/** All declared path keys (e.g. "/v1/execution-control/evaluate"). Useful for consumers building route tables. */\n` +
  `export const OPENAPI_PATHS: ReadonlyArray<string> = Object.freeze(${JSON.stringify(Object.keys(parsed.paths ?? {}).sort())});\n`;

writeFileSync(embeddedTs, content, "utf8");

const rel = (p) => relative(pkgRoot, p).replace(/\\/g, "/");
console.log(`embed-openapi: wrote ${rel(localCopy)} (${canonical.length} bytes)`);
console.log(`embed-openapi: wrote ${rel(embeddedTs)} (${content.length} bytes, ${Object.keys(parsed.paths ?? {}).length} paths embedded)`);
