{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aristotle.serviceAccountName" . }}
  namespace: {{ include "aristotle.namespace" . }}
  labels:
{{ include "aristotle.commonLabels" . | indent 4 }}
{{- if .Values.identity.spiffe.enabled }}
  annotations:
    spiffe.io/spiffe-id: "spiffe://{{ .Values.identity.spiffe.trustDomain }}/ns/{{ include "aristotle.namespace" . }}/sa/{{ include "aristotle.serviceAccountName" . }}"
{{- end }}
{{- end }}
