{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ include "aristotle.namespace" $ }}
  labels:
{{ include "aristotle.commonLabels" $ | indent 4 }}
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
{{- end }}
